### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by godblesshugh** [awesome-fc/golang-runtime#7]
message: 
goroutine 1529 [running]:
github.com/awesome-fc/golang-runtime.GetLoggerByRequestID({0xc000468571, 0x20})
	/xxxxxxxxxxxxxxxxxxxxxxxxxx/github.com/awesome-fc/golang-runtime@v0.0.0-20220629090431-93c1f92c7353/fc_logger.go:60 +0x13e
github.com/awesome-fc/golang-runtime.NewFromContext(0xc000708f00)
	/xxxxxxxxxxxxxxxxxxxxxxxxxx/github.com/awesome-fc/golang-runtime@v0.0.0-20220629090431-93c1f92c7353/fc_context.go:101 +0x394
github.com/awesome-fc/golang-runtime.invokeHandler({0x10469c0, 0xc000787180}, 0xc000708f00)
	/xxxxxxxxxxxxxxxxxxxxxxxxxx/github.com/awesome-fc/golang-runtime@v0.0.0-20220629090431-93c1f92c7353/server.go:34 +0x1d1
github.com/awesome-fc/golang-runtime.handle({0x10469c0, 0xc000787180}, 0xc000708f00)
	/xxxxxxxxxxxxxxxxxxxxxxxxxx/github.com/awesome-fc/golang-runtime@v0.0.0-20220629090431-93c1f92c7353/server.go:68 +0x8d
net/http.HandlerFunc.ServeHTTP(0xc000787180?, {0x10469c0?, 0xc000787180?}, 0xee3b34?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x10469c0, 0xc000787180}, 0xc000708f00)
	/usr/local/go/src/net/http/server.go:2487 +0x149
net/http.serverHandler.ServeHTTP({0x1044f68?}, {0x10469c0, 0xc000787180}, 0xc000708f00)
	/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0006688c0, {0x1047438, 0xc0000acf00})
	/usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x4db

**Comment by godblesshugh** [comment]
剩下的都是非running状态
fc_logger.go 里面定义的 var logMap map[string]*logrus.Entry 并发读写了

**Comment by PandaTtttt** [comment]
我也遇到了，希望尽快修复下。
I also encountered it, I hope to repair it as soon as possible.
